name: CI

on:
  push:
    branches: [ "**" ]
    paths-ignore: [ "*.md", "docs/**" ]
  pull_request:
    branches: [ "**" ]
    paths-ignore: [ "*.md", "docs/**" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'   # change to 'gradle' if using Gradle

      - name: Build & test (Maven)
        if: hashFiles('**/pom.xml') != ''
        run: mvn -B -ntp clean verify

      - name: Build & test (Gradle)
        if: hashFiles('**/build.gradle*') != ''
        run: |
          chmod +x ./gradlew
          ./gradlew clean test jacocoTestReport

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/target/surefire-reports/**/*
            **/target/failsafe-reports/**/*
            **/build/test-results/**/*
          retention-days: 7

      - name: Upload coverage (JaCoCo)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/target/site/jacoco/**/*
            **/build/reports/jacoco/**/*
          retention-days: 7
