# application-prod.yml
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/members_db
      auto-index-creation: true
    web:
      page-serialization-mode: via_dto

  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
app:
  mail:
    from: "no-reply@kitchensink.com"
    approveBaseUrl: "http://localhost:8080"
    loginUrl: "http://localhost:8080/auth/login"
  admin:
    email: admin@kitchensink.com